version: '3.8'
services:
  ms-validador-jwt:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ms-validador-jwt:latest
    ports:
      - "8080:8080"
    environment:
      - ZIPKIN_URL=http://zipkin:9411/
    networks:
      - tracing-network
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - tracing-network

networks:
  tracing-network:
    driver: bridge